name: Test and Deploy To Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'images/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install uv
        run: pip install uv

      - name: Install pytest
        run: pip install pytest

      - name: Sync dependencies
        run: uv sync || pip install -r requirements.txt

      - name: Verify Installed Packages
        run: pip list

      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings -q

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync || pip install -r requirements.txt

      - name: Deploy to Render
        run: curl -X GET "https://api.render.com/deploy/srv-cur1eea3esus739u38k0?key=${{ secrets.RENDER_API_KEY }}"
