name: Test and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'images/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

  deploy:
    needs: test  # Deployment runs only if tests pass
    runs-on: ubuntu-latest
    if: success()  # Ensures deployment does not run if tests fail

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render
        run: |
          curl -X GET "https://api.render.com/deploy/srv-cur1eea3esus739u38k0?key=${{ secrets.RENDER_API_KEY }}"